const express = require('express');
const router = express.Router();
const upload = require('../middleware/uploadMiddleware');

router.post('/upload', upload.single('image'), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: 'No file uploaded' });
  }
  // req.file.path contains the public secure URL generated by Cloudinary
  res.status(200).json({ 
    message: 'File uploaded successfully', 
    url: req.file.path 
  });
});

module.exports = router;